// Generated by map_editor.html — node & trail positions for worldmap_bg.png
window.NQ_MAP_OVERRIDE = {
 "nodes": {
  "vale": {
   "x": 146,
   "y": 181
  },
  "coast": {
   "x": 330,
   "y": 188
  },
  "wastes": {
   "x": 355,
   "y": 111
  },
  "canyon": {
   "x": 228,
   "y": 68
  }
 },
 "paths": {
  "2-3": [
   [
    267,
    100
   ]
  ],
  "1-2": [
   [
    364,
    147
   ]
  ],
  "0-1": [
   [
    239,
    182
   ],
   [
    276,
    187
   ]
  ]
 }
};
