"use strict";
// ============== THE COGWERK ROADS — side-scroll interludes between city stages ==============
// First trip between Cogwerk levels runs a bopping side-scroller. v2: full factory set-pieces
// (conveyors, crushers, steam vents, spark-bobs), a five-flap wing meter, and three BESPOKE
// boss fights — each with its own attacks and its own moment of vulnerability:
//   PISTON PETE  — armored head; slam-waves + steam jets; bop him while his fist is STUCK.
//   GASKETTA     — hangs from the pipes; steam-rain + wrenches; bop her when she overheats and FALLS.
//   THE RAIL KING— surfs a spark-cart; spark showers + a magnet crown; bop him when the cart TIPS.
(function () {
  const seg = (s) => s.split('\n').filter(r => r.length);
  const join = (segs) => {
    for (const sg of segs) {
      if (sg.length !== ROAD_H) throw new Error('road seg is ' + sg.length + ' rows, wants ' + ROAD_H + ':\n' + sg.join('\n'));
      for (const r of sg) if (r.length !== sg[0].length) throw new Error('ragged road seg row: "' + r + '"');
    }
    const rows = [];
    for (let j = 0; j < ROAD_H; j++) rows.push(segs.map(sg => sg[j]).join(''));
    return rows;
  };
  const norm = (def) => {
    const w = Math.max(...def.rows.map(r => r.length));
    def.rows = def.rows.map(r => r.padEnd(w, ' '));
    def.w = w;
    return def;
  };

  // ---- 1. THE GEAR-LINE (cog1 -> cog2): conveyor runs, crusher corridor, vent hopscotch ----
  ROAD_LEVELS.gearline = norm({
    name: 'THE GEAR-LINE', theme: 'cogwerk', boss: 'pistonpete', gravity: 1,
    intro: 'THE GEAR-LINE! Ride the belts, duck the stampers, hop the steam — PISTON PETE guards the far gate!',
    rows: join([
seg(`
..............
..............
..............
..............
..............
..............
..............
.....o........
....ooo.......
..............
..............
..............
##############
##############`),
seg(`
........................
........................
........................
........................
..........o.o.o.........
........................
........................
........................
...w..............w.....
........................
........................
........................
####>>>>>>>>>>>>>>>>####
########################`),
seg(`
........................
........................
........................
........................
........o....o..........
........................
........................
........................
......=....=....=.......
........................
..............h.........
........................
##^^<<<<<<<<<<<<<<<<####
########################`),
seg(`
..........................
..........................
..........................
....C.....C.....C.........
..........................
..........................
..........................
..........................
.......o.....o............
..........................
..w..................w....
..........................
##########################
##########################`),
seg(`
............
............
............
............
....o.o.....
............
..........o.
....===.....
............
............
..F...S.....
............
############
############`),
seg(`
..........................
..........................
..........................
..........................
........f........f........
..........................
...o......o......o........
..........................
..==....==....==....==....
..........................
..........................
.....V.....V.....V.....V..
##########################
##########################`),
seg(`
..........................
..........................
..........................
.........C................
..........................
.....o..........o.........
..........................
....................d.....
..........................
..........................
..........................
..........................
##>>>>>>>>>>>>############
##########################`),
seg(`
..........
..........
..........
..........
..........
..........
..........
..........
....o.....
..........
..F.......
..........
##########
##########`),
seg(`
.............................#
.............................#
.............................#
.............................#
.............................#
.............................#
.............................#
.............................#
....o...o...o................#
.............................#
...====...........G..........#
.............................#
##############################
##############################`),
    ]),
  });

  // ---- 2. THE STEAMWAY (cog2 -> cog3): vent rhythms, spark-shafts, the pipe-press ----
  ROAD_LEVELS.steamway = norm({
    name: 'THE STEAMWAY', theme: 'cogwerk', boss: 'gasketta', gravity: 1,
    intro: 'THE STEAMWAY! The pipes hiss in rhythm — wait out the vents, slip the spark-orbs, and beware GASKETTA on her ceiling!',
    rows: join([
seg(`
..............
..............
..............
..............
..............
.....o........
..............
...====.......
..............
..............
....f.........
..............
##############
##############`),
seg(`
......................
......................
......................
........o......o......
......................
....====......====....
......................
......................
..............f.......
......................
......................
.....V......V.........
######################
######################`),
seg(`
........................
........................
........................
......o.....o.....o.....
........................
....===...===...===.....
........................
.........Z.....Z........
........................
...h................h...
........................
........................
###....####....#########
###....####....#########`),
seg(`
............
............
............
............
............
......o.....
............
............
............
............
..F...S.....
............
############
############`),
seg(`
........................
........................
........................
......C........C........
........................
........................
........o.......o.......
........................
........................
........................
..w.............w.......
........................
##<<<<<<<<<<<<<<<<<<####
########################`),
seg(`
........................
........................
.......o..o..o..........
........................
.....====....====.......
........................
........................
...............f........
........................
........................
....V.....V.....V.......
........................
########################
########################`),
seg(`
..........
..........
..........
..........
..........
..........
..........
..........
....o.....
..........
..F.......
..........
##########
##########`),
seg(`
##############################
##############################
...........................###
...........................###
...........................###
...........................###
...........................###
...........................###
........o....o.............###
...........................###
..................G........###
...........................###
##############################
##############################`),
    ]),
  });

  // ---- 3. THE SKY-RAIL (cog3 -> cog4): low gravity, skinny rails, a LONG way down ----
  ROAD_LEVELS.skyrail = norm({
    name: 'THE SKY-RAIL', theme: 'cogwerk', boss: 'railking', gravity: 0.86, wings: 1,
    intro: 'THE SKY-RAIL! Five flaps, then you glide — spend them wisely over the void, and dethrone THE RAIL KING!',
    rows: join([
seg(`
............
............
............
............
............
......o.....
............
............
............
............
............
............
############
############`),
seg(`
..........................
..........................
..........................
..........................
.....o.........o..........
..........................
...===.........===........
..........................
..........o...............
..........................
........===........===....
..........................
###.......................
###.......................`),
seg(`
............
............
............
............
............
.....o......
............
............
............
............
..F..S......
............
############
############`),
seg(`
........................
........................
........................
......o.....o...........
........................
....===....===....===...
........................
.........Z......Z.......
........................
........f...............
........................
........................
........................
........................`),
seg(`
............................
............................
.........o..o..o............
........o........o..........
............................
............................
.............===............
............................
......Z..............Z......
.......===........===.......
............................
............................
###......................###
###......................###`),
seg(`
............
............
............
............
............
....o.......
............
............
............
............
..F.........
............
############
############`),
seg(`
.............................#
.............................#
.............................#
.............................#
.............................#
.............................#
......====.........====......#
.............................#
.............................#
........o.....o..............#
.............................#
..................G..........#
##############################
##############################`),
    ]),
  });

  // enemies + bosses for the cogwerk theme
  ROAD_ENEMY_SPECIES.cogwerk = { w: 'voltbug', h: 'coghopper', f: 'sparkdrone', d: 'steambull' };
  ROAD_BOSS_SPECIES.pistonpete = 'steambull';  ROAD_BOSS_NAMES.pistonpete = 'PISTON PETE';        ROAD_BOSS_HP.pistonpete = 3;
  ROAD_BOSS_SPECIES.gasketta   = 'sparkdrone'; ROAD_BOSS_NAMES.gasketta   = 'GASKETTA THE GUST';  ROAD_BOSS_HP.gasketta   = 3;
  ROAD_BOSS_SPECIES.railking   = 'coghopper';  ROAD_BOSS_NAMES.railking   = 'THE RAIL KING';      ROAD_BOSS_HP.railking   = 4;

  const SS = SideScroll;
  SS.BOSS_INTRO.pistonpete = 'PISTON PETE blocks the line! Jump his floor-waves — when his FIST STICKS, bop his head!';
  SS.BOSS_INTRO.gasketta   = 'GASKETTA clings to the pipes! Stand in the gaps of her steam-rain — when she overheats and FALLS, bop her!';
  SS.BOSS_INTRO.railking   = 'THE RAIL KING surfs his spark-cart! Dodge the sparks, fight his magnet — when the cart TIPS, bop him!';

  // ================= PISTON PETE: slam-waves, steam jets, and a fist that gets STUCK =================
  SS.BOSS_AI.pistonpete = function (S, b, dt, ss) {
    const p = S.p, groundY = ss.groundYAt(S, b.x);
    b.vy = (b.vy || 0) + 760 * dt; b.y = Math.min(groundY, b.y + b.vy * dt); if (b.y >= groundY) b.vy = 0;
    b.ph = b.ph || 'stride'; b.phT = (b.phT || 0) + dt;
    b.waves = b.waves || []; b.jets = b.jets || [];
    if (b.ph === 'stride') {
      b.x += Math.sign(p.x - b.x) * 26 * dt;
      if (b.phT > 1.05) { b.ph = 'wind'; b.phT = 0; Audio2.jingle('denied'); }
    } else if (b.ph === 'wind') {
      if (b.phT > 0.5) {
        b.ph = 'stride'; b.phT = 0;
        b.slams = (b.slams || 0) + 1;
        S.shake = 0.3; Audio2.jingle('rumble'); Particles.burst(b.x, b.y, 'dust');
        if (b.slams % 3 === 0) { b.stun = 1.9; b.stuck = 1; }               // the BOP window
        else {
          b.waves.push({ x: b.x, dir: Math.sign(p.x - b.x) || 1, t: 0 });
          if (b.slams % 3 === 2) b.jets.push({ x: Math.round(p.x / 16) * 16 + 8, t: -0.6 });  // steam at YOUR column
        }
      }
    }
    if (b.stun <= 0) b.stuck = 0;
    for (let i = b.waves.length - 1; i >= 0; i--) {     // floor-waves roll along the ground — jump them
      const w = b.waves[i]; w.t += dt; w.x += w.dir * 150 * dt;
      const gy = ss.groundYAt(S, w.x);
      if (w.t > 2.4 || ss.solidAt(S, w.x + w.dir * 6, gy - 8)) { b.waves.splice(i, 1); continue; }
      if (p.inv <= 0 && Math.abs(p.x - w.x) < 8 && p.y > gy - 14) ss.hurt(S, 1);
    }
    for (let i = b.jets.length - 1; i >= 0; i--) {      // warned steam jets, tall enough to cook hoverers
      const jt = b.jets[i]; jt.t += dt;
      if (jt.t > 0.75) { b.jets.splice(i, 1); continue; }
      if (jt.t > 0 && p.inv <= 0) {
        const gy = ss.groundYAt(S, jt.x);
        if (Math.abs(p.x - jt.x) < 9 && p.y > gy - 82) ss.hurt(S, 1);
      }
    }
    // armored head: stomps CLANG off unless the fist is stuck
    if (Math.abs(p.x - b.x) < 17 && Math.abs((p.y - 8) - (b.y - 10)) < 18) {
      if (p.vy > 40 && p.y - 8 < b.y - 8) {
        p.vy = -240; p.inv = Math.max(p.inv, 0.3);
        Audio2.jingle('denied'); Particles.burst(b.x, b.y - 20, 'sparkle');
      } else if (p.inv <= 0) ss.hurt(S, 1);
    }
  };
  SS.BOSS_DRAW.pistonpete = function (c, S, b, ss) {
    for (const w of b.waves || []) {
      const gy = ss.groundYAt(S, w.x);
      c.fillStyle = '#8a6c3c'; c.beginPath(); c.moveTo(w.x - 9, gy); c.quadraticCurveTo(w.x, gy - 15, w.x + 9, gy); c.fill();
      c.fillStyle = '#c8a04c'; c.beginPath(); c.moveTo(w.x - 6, gy); c.quadraticCurveTo(w.x, gy - 11, w.x + 6, gy); c.fill();
      c.fillStyle = 'rgba(255,255,255,.4)'; c.beginPath(); c.arc(w.x - w.dir * 4, gy - 9, 2, 0, 7); c.fill();
    }
    for (const jt of b.jets || []) {
      const gy = ss.groundYAt(S, jt.x);
      if (jt.t <= 0) {
        if (((jt.t * 8 | 0) % 2) === 0) { c.strokeStyle = 'rgba(255,120,80,.9)'; c.lineWidth = 2; c.beginPath(); c.ellipse(jt.x, gy - 2, 9, 3, 0, 0, 7); c.stroke(); }
      } else {
        c.fillStyle = 'rgba(235,244,255,.85)'; c.fillRect(jt.x - 5, gy - 80, 10, 80);
        c.fillStyle = '#fff'; c.fillRect(jt.x - 2, gy - 80, 4, 80);
      }
    }
    const set = Sprites.creatures.steambull;
    const spr = ((S.p.x > b.x) ? set.right : set.left)[((b.t * 4 | 0) % 2)];
    c.save();
    c.translate(Math.round(b.x), Math.round(b.y));
    if (b.inv > 0 && ((b.inv * 14 | 0) % 2)) c.globalAlpha = 0.4;
    if (b.ph === 'wind') c.translate(Math.random() * 2 - 1, -3);
    c.fillStyle = 'rgba(20,10,40,.35)'; c.beginPath(); c.ellipse(0, 0, 15, 3.6, 0, 0, 7); c.fill();
    const lift = b.ph === 'wind' ? -27 : b.stuck ? 1 : -8;     // fist pads: raised, buried, or carried
    for (const sx of [-18, 18]) {
      c.fillStyle = '#241a33'; c.fillRect(sx - 3, lift - 13, 6, 14);   // piston rod
      c.fillStyle = '#8a94a8'; c.fillRect(sx - 2, lift - 12, 4, 12);
      c.fillStyle = '#241a33'; c.fillRect(sx - 7, lift, 14, 7);        // the FIST
      c.fillStyle = '#c8a04c'; c.fillRect(sx - 6, lift + 1, 12, 5);
      c.fillStyle = '#e8c060'; c.fillRect(sx - 6, lift + 1, 12, 2);
      if (b.stuck) { c.fillStyle = 'rgba(200,160,80,.8)'; c.fillRect(sx - 8, 4, 16, 3); }   // buried in the floor
    }
    c.scale(2.3, 2.3);
    dspr(c, spr, -sprW(spr) / 2, -sprH(spr));
    c.restore();
    if (b.stun > 0) drawText(c, '@..@', b.x - 9, b.y - 58, 8, '#f8e858', '#241a33');
    ss.drawBossPips(c, b, b.x, b.y - 66);
  };
  SS.BOSS_HINT.pistonpete = (S, b) =>
    b.stun > 0 ? 'FIST STUCK! BOP HEAD!'
    : (b.jets || []).some(j => j.t <= 0) ? 'STEAM! STEP AWAY!'
    : (b.waves || []).length ? 'JUMP THE WAVE!'
    : b.ph === 'wind' ? 'FIST UP! GET READY!'
    : 'WATCH THE FIST!';

  // ================= GASKETTA: ceiling-crawler, steam-rain, overheat drops =================
  SS.BOSS_AI.gasketta = function (S, b, dt, ss) {
    const p = S.p;
    const ceilY = (x) => {          // the underside of the arena's pipe-ceiling
      const i = Math.floor(x / ROAD_TILE);
      let j = 0;
      while (j < 6 && !ROAD_SOLID[ss.tile(S, i, j)]) j++;
      if (j >= 6) return 34;
      while (j < 6 && ROAD_SOLID[ss.tile(S, i, j)]) j++;
      return j * ROAD_TILE;
    };
    b.ph = b.ph || 'scuttle'; b.phT = (b.phT || 0) + dt;
    b.rains = b.rains || 0; b.cols = b.cols || []; b.shots = b.shots || [];
    const hangY = ceilY(b.x) + 14;
    if (b.ph === 'scuttle') {
      b.y += clamp(hangY + Math.sin(b.t * 3) * 3 - b.y, -130 * dt, 130 * dt);
      b.x += clamp(p.x - b.x, -64, 64) * dt;
      if (b.phT > 1.2 && !b.thrown && b.rains > 0) {          // one wrench per lap once she's warm
        b.thrown = 1;
        b.shots.push({ x: b.x, y: b.y + 8, vx: clamp((p.x - b.x) * 1.1, -130, 130), vy: 40, t: 0 });
        Audio2.jingle('step');
      }
      if (b.phT > 2.0) {
        if (b.rains >= 2) { b.ph = 'drop'; b.phT = 0; b.vy = 30; Audio2.jingle('denied'); }
        else {
          b.ph = 'rain'; b.phT = 0; b.cols = [];
          const pi = Math.round(p.x / 16);
          for (const off of [0, -3, 3]) b.cols.push({ x: (pi + off) * 16 + 8, t: -0.85 });
          Audio2.jingle('push');
        }
      }
    } else if (b.ph === 'rain') {
      let done = true;
      for (const cl of b.cols) {
        cl.t += dt; if (cl.t < 1.1) done = false;
        if (cl.t > 0 && cl.t < 1.1 && p.inv <= 0 && Math.abs(p.x - cl.x) < 8) ss.hurt(S, 1);
      }
      if (done) { b.ph = 'scuttle'; b.phT = 0; b.thrown = 0; b.rains++; b.cols = []; }
    } else if (b.ph === 'drop') {
      b.vy += 700 * dt; b.y += b.vy * dt;
      const gy = ss.groundYAt(S, b.x);
      if (b.y >= gy) {
        b.y = gy; b.vy = 0; b.ph = 'floor'; b.stun = 2.2; b.rains = 0;
        S.shake = 0.3; Audio2.jingle('rumble'); Particles.burst(b.x, b.y, 'dust');
      }
    } else if (b.ph === 'floor') {                             // stun spent -> fly home
      b.y += clamp(hangY - b.y, -140 * dt, 140 * dt);
      if (Math.abs(b.y - hangY) < 3) { b.ph = 'scuttle'; b.phT = 0; }
    }
    for (let i = b.shots.length - 1; i >= 0; i--) {            // wrenches arc down
      const sh = b.shots[i]; sh.t += dt; sh.vy += 520 * dt; sh.x += sh.vx * dt; sh.y += sh.vy * dt;
      if (sh.y > ss.groundYAt(S, sh.x) + 4 || sh.t > 3) { Particles.burst(sh.x, sh.y, 'dust'); b.shots.splice(i, 1); continue; }
      if (p.inv <= 0 && Math.abs(p.x - sh.x) < 8 && Math.abs((p.y - 8) - sh.y) < 9) { ss.hurt(S, 1); b.shots.splice(i, 1); }
    }
    if (b.ph !== 'floor') ss.bossTouch(S, b, false);           // the ceiling is HERS — no free stomps up there
  };
  SS.BOSS_DRAW.gasketta = function (c, S, b, ss) {
    for (const cl of b.cols || []) {
      const gy = ss.groundYAt(S, cl.x);
      if (cl.t <= 0) {
        if (((cl.t * 8 | 0) % 2) === 0) { c.strokeStyle = 'rgba(154,220,248,.9)'; c.lineWidth = 2; c.beginPath(); c.ellipse(cl.x, gy - 2, 9, 3, 0, 0, 7); c.stroke(); }
        c.fillStyle = 'rgba(154,220,248,.25)'; c.fillRect(cl.x - 2, 30, 4, gy - 30);
      } else if (cl.t < 1.1) {
        c.fillStyle = 'rgba(235,244,255,.85)'; c.fillRect(cl.x - 6, 30, 12, gy - 30);
        c.fillStyle = '#fff'; c.fillRect(cl.x - 2, 30, 4, gy - 30);
      }
    }
    for (const sh of b.shots || []) {
      c.save(); c.translate(sh.x, sh.y); c.rotate(sh.t * 9);
      c.fillStyle = '#241a33'; c.fillRect(-6, -2, 12, 4); c.fillRect(2, -4, 4, 8);
      c.fillStyle = '#8a94a8'; c.fillRect(-5, -1, 10, 2); c.fillRect(3, -3, 2, 6);
      c.restore();
    }
    const set = Sprites.creatures.sparkdrone;
    const spr = ((S.p.x > b.x) ? set.right : set.left)[((b.t * 4 | 0) % 2)];
    const up = b.ph !== 'floor' && b.ph !== 'drop';
    c.save();
    c.translate(Math.round(b.x), Math.round(b.y));
    if (b.inv > 0 && ((b.inv * 14 | 0) % 2)) c.globalAlpha = 0.4;
    if (up) {
      c.strokeStyle = '#241a33'; c.lineWidth = 2;              // grip arms up to the pipes
      c.beginPath(); c.moveTo(-6, -10); c.lineTo(-9, -16); c.moveTo(6, -10); c.lineTo(9, -16); c.stroke();
      c.scale(2.3, 2.3); c.scale(1, -1);                       // she hangs upside-down
      dspr(c, spr, -sprW(spr) / 2, -sprH(spr));
    } else {
      c.fillStyle = 'rgba(20,10,40,.35)'; c.beginPath(); c.ellipse(0, 0, 13, 3.2, 0, 0, 7); c.fill();
      c.scale(2.3, 2.3);
      dspr(c, spr, -sprW(spr) / 2, -sprH(spr));
    }
    c.restore();
    const heat = b.stun > 0 ? 0 : (b.rains || 0) / 2;          // her gasket glows hotter — the tell she'll fall
    if (heat > 0) {
      c.fillStyle = 'rgba(232,74,74,' + (0.35 + 0.4 * heat) + ')';
      c.beginPath(); c.arc(b.x, b.y + (up ? 6 : -14), 4 + heat * 2 + Math.sin(b.t * 8) * 1.2, 0, 7); c.fill();
    }
    if (b.stun > 0) drawText(c, '@..@', b.x - 9, b.y - 44, 8, '#f8e858', '#241a33');
    ss.drawBossPips(c, b, b.x, b.y - (up ? 26 : 52));
  };
  SS.BOSS_HINT.gasketta = (S, b) =>
    b.stun > 0 ? 'SHE FELL! BOP HER!'
    : b.ph === 'rain' ? 'STAND IN A GAP!'
    : (b.shots || []).length ? 'JUMP THE WRENCH!'
    : (b.rains || 0) >= 2 ? 'RED HOT! WATCH HER!'
    : 'WATCH THE CEILING!';

  // ================= THE RAIL KING: spark-cart surfing, a magnet crown, derail windows =================
  SS.BOSS_AI.railking = function (S, b, dt, ss) {
    const p = S.p, grav = 760 * S.def.gravity;
    b.ph = b.ph || 'surf'; b.phT = (b.phT || 0) + dt;
    b.shots = b.shots || []; b.dir = b.dir || -1;
    const gy = ss.groundYAt(S, b.x);
    if (b.ph === 'surf') {
      b.x += b.dir * 108 * dt;
      b.vy = (b.vy || 0) + grav * dt; b.y = Math.min(gy, b.y + b.vy * dt); if (b.y >= gy) b.vy = 0;
      const aL = (S.bossHome[0] - 14) * ROAD_TILE + 24, aR = S.def.w * ROAD_TILE - 24;
      if (b.x < aL) { b.x = aL; b.dir = 1; } else if (b.x > aR) { b.x = aR; b.dir = -1; }
      b.spkT = (b.spkT || 0) - dt;
      if (b.spkT <= 0 && b.y >= gy - 2) {                      // sparks fly off the back of the cart
        b.spkT = 0.24;
        b.shots.push({ x: b.x - b.dir * 10, y: b.y - 10, vx: -b.dir * (30 + Math.random() * 50), vy: -(70 + Math.random() * 90), t: 0 });
      }
      if (Math.abs(p.x - b.x) > 96 && b.y >= gy - 2 && b.phT > 1.2) {   // long cart-hop back over Noah
        b.vy = -250; b.dir = Math.sign(p.x - b.x) || b.dir; b.phT = 0.6; Audio2.jingle('flap');
      }
      if (b.phT > 3.0) { b.ph = 'brake'; b.phT = 0; Audio2.jingle('denied'); }
    } else if (b.ph === 'brake') {
      b.y = gy;
      if (b.phT > 0.55) { b.ph = 'magnet'; b.phT = 0; Audio2.jingle('push'); }
    } else if (b.ph === 'magnet') {
      b.y = gy;
      p.vx += Math.sign(b.x - p.x) * 300 * dt;                 // the crown DRAGS you — run or flap away!
      if (b.phT > 1.15) {
        b.ph = 'surf'; b.phT = 0;
        b.pulls = (b.pulls || 0) + 1;
        if (b.pulls % 2 === 0) {                               // every 2nd pull the crown overloads: DERAIL
          b.stun = 2.3; b.derail = 1;
          S.shake = 0.35; Audio2.jingle('rumble'); Particles.burst(b.x, b.y, 'dust');
        }
      }
    }
    if (b.stun <= 0) b.derail = 0;
    for (let i = b.shots.length - 1; i >= 0; i--) {            // the spark shower bounces once
      const sh = b.shots[i]; sh.t += dt; sh.vy += grav * 0.55 * dt; sh.x += sh.vx * dt; sh.y += sh.vy * dt;
      const sgy = ss.groundYAt(S, sh.x);
      if (sh.y > sgy + 2) { sh.vy = -Math.abs(sh.vy) * 0.35; sh.y = sgy; sh.bounced = (sh.bounced || 0) + 1; }
      if (sh.t > 2.2 || sh.bounced > 1) { b.shots.splice(i, 1); continue; }
      if (p.inv <= 0 && Math.abs(p.x - sh.x) < 7 && Math.abs((p.y - 8) - sh.y) < 8) { ss.hurt(S, 1); b.shots.splice(i, 1); }
    }
    ss.bossTouch(S, b, false);                                 // his crown is spiky — no free stomps
  };
  SS.BOSS_DRAW.railking = function (c, S, b, ss) {
    for (const sh of b.shots || []) {
      c.fillStyle = '#241a33'; c.beginPath(); c.arc(sh.x, sh.y, 4, 0, 7); c.fill();
      c.fillStyle = '#f89238'; c.beginPath(); c.arc(sh.x, sh.y, 3, 0, 7); c.fill();
      c.fillStyle = '#f8e858'; c.beginPath(); c.arc(sh.x - 0.5, sh.y - 0.5, 1.4, 0, 7); c.fill();
    }
    const set = Sprites.creatures.coghopper;
    const spr = ((S.p.x > b.x) ? set.right : set.left)[((b.t * 6 | 0) % 2)];
    c.save();
    c.translate(Math.round(b.x), Math.round(b.y));
    if (b.inv > 0 && ((b.inv * 14 | 0) % 2)) c.globalAlpha = 0.4;
    c.fillStyle = 'rgba(20,10,40,.35)'; c.beginPath(); c.ellipse(0, 0, 14, 3.4, 0, 0, 7); c.fill();
    if (b.derail) c.rotate(0.5);
    c.fillStyle = '#241a33'; c.fillRect(-14, -8, 28, 8);       // the spark-cart
    c.fillStyle = '#c8743c'; c.fillRect(-13, -7, 26, 6);
    c.fillStyle = '#f8d048'; c.fillRect(-13, -7, 26, 2);
    c.fillStyle = '#241a33'; c.beginPath(); c.arc(-8, 0, 3.4, 0, 7); c.arc(8, 0, 3.4, 0, 7); c.fill();
    c.fillStyle = '#8a94a8'; c.beginPath(); c.arc(-8, 0, 1.6, 0, 7); c.arc(8, 0, 1.6, 0, 7); c.fill();
    c.save(); c.translate(0, -7); c.scale(2.1, 2.1); dspr(c, spr, -sprW(spr) / 2, -sprH(spr)); c.restore();
    const hot = b.ph === 'brake' || b.ph === 'magnet';
    const cy = -7 - sprH(spr) * 2.1;                           // the crown, blinking hot before the pull
    c.fillStyle = (hot && ((b.t * 10 | 0) % 2)) ? '#e84a4a' : '#f8d048';
    c.beginPath(); c.moveTo(-6, cy); c.lineTo(-6, cy - 6); c.lineTo(-3, cy - 2); c.lineTo(0, cy - 7); c.lineTo(3, cy - 2); c.lineTo(6, cy - 6); c.lineTo(6, cy); c.fill();
    c.restore();
    if (b.ph === 'magnet') {                                   // the field reaches for Noah
      const p = S.p;
      c.strokeStyle = 'rgba(248,208,72,.6)'; c.lineWidth = 1;
      for (let k = 1; k <= 4; k++) {
        const mx = lerp(p.x, b.x, k / 5), wob = Math.sin(S.t * 14 + k) * 3;
        c.beginPath(); c.moveTo(mx, p.y - 10 + wob); c.lineTo(mx + Math.sign(b.x - p.x) * 6, p.y - 10 + wob); c.stroke();
      }
    }
    if (b.stun > 0) drawText(c, '@..@', b.x - 9, b.y - 50, 8, '#f8e858', '#241a33');
    ss.drawBossPips(c, b, b.x, b.y - 58);
  };
  SS.BOSS_HINT.railking = (S, b) =>
    b.stun > 0 ? 'CART TIPPED! BOP HIM!'
    : b.ph === 'magnet' ? 'MAGNET! RUN AWAY!'
    : b.ph === 'brake' ? 'MAGNET SOON!'
    : 'DODGE THE SPARKS!';
})();

// ---- World-3 travel: Noah WALKS the painted map, and the roads ambush him halfway ----
// (same recipe as the World-1 overworld: point-path, per-leg midpoints, resume on a win)
const W3_CHAIN = ['cog1', 'cog2', 'cog3', 'cog4'];       // the main brass trail
const W3_SPURS = { stable: 'cog1' };                     // side-paths hang off a chain stop (peaceful)
const COG_ROUTES = { 'cog1-cog2': 'gearline', 'cog2-cog3': 'steamway', 'cog3-cog4': 'skyrail' };
const n3 = (id) => WORLD3_NODES.find(n => n.id === id);

Game.world3Go = function (n) {
  if (this.world3Travel) return;                          // already walking
  const hereId = WORLD3_NODES[this.world3Here()].id;
  if (n.exit) { this.state = 'play'; this.loadMap('vale'); saveGame(); return; }
  if (n.id === hereId) { this.state = 'play'; this.loadMap(n.id); saveGame(); return; }
  // node route: spur out -> along the chain -> spur in
  const chainOf = (id) => W3_SPURS[id] || id;
  const route = [hereId];
  if (W3_SPURS[hereId]) route.push(W3_SPURS[hereId]);
  const a = W3_CHAIN.indexOf(chainOf(hereId)), b = W3_CHAIN.indexOf(chainOf(n.id));
  const stp = b > a ? 1 : -1;
  if (a !== b) for (let i = a + stp; stp > 0 ? i <= b : i >= b; i += stp) route.push(W3_CHAIN[i]);
  if (W3_SPURS[n.id]) route.push(n.id);
  const ids = route.filter((id, i) => id !== route[i - 1]);
  // densified straight legs (12 steps each) so every leg has a real midpoint
  const pts = [], legs = [];
  for (let i = 1; i < ids.length; i++) {
    const A = n3(ids[i - 1]), B = n3(ids[i]);
    const startSeg = pts.length ? pts.length - 1 : 0;
    for (let k = pts.length ? 1 : 0; k <= 12; k++) pts.push([lerp(A.x, B.x, k / 12), lerp(A.y, B.y, k / 12)]);
    legs.push({ key: [ids[i - 1], ids[i]].sort().join('-'), startSeg, endSeg: pts.length - 1 });
  }
  this.world3Travel = { pts, seg: 0, x: pts[0][0], y: pts[0][1], target: n.id, anim: 0, dir: 'down', legs };
  Audio2.jingle('step');
};
Game.updateWorld3Travel = function (dt) {
  const tv = this.world3Travel; if (!tv) return;
  tv.anim += dt;
  const next = tv.pts[tv.seg + 1];
  if (!next) {
    const id = tv.target; this.world3Travel = null;
    this.state = 'play'; this.loadMap(id); saveGame(); return;
  }
  const d = dist(tv.x, tv.y, next[0], next[1]);
  const spd = 95 * dt;
  if (d <= spd) {
    tv.x = next[0]; tv.y = next[1]; tv.seg++;
    // TROUBLE ON THE GEAR-ROADS: halfway along each leg, an ambush (once per route)
    for (const leg of tv.legs) {
      const mid = (leg.startSeg + leg.endSeg) >> 1;
      const road = COG_ROUTES[leg.key];
      if (road && tv.seg === mid && !this.flags['road_' + road]) {
        this.pendingCog3 = tv; this.world3Travel = null;
        SideScroll.start(road, true);
        return;
      }
    }
  } else {
    tv.x += (next[0] - tv.x) / d * spd; tv.y += (next[1] - tv.y) / d * spd;
    tv.dir = Math.abs(next[0] - tv.x) > Math.abs(next[1] - tv.y) ? (next[0] > tv.x ? 'right' : 'left') : (next[1] > tv.y ? 'down' : 'up');
  }
};
if (typeof G !== 'undefined' && G.NQ) { G.NQ.COG_ROUTES = COG_ROUTES; G.NQ.W3_CHAIN = W3_CHAIN; G.NQ.W3_SPURS = W3_SPURS; }
